### ISSUE TITLE
Consulting  TDMX_ Template. m code

### ISSUE THREAD

**Issue by Fraserzws** [RaichleLab/lag-code#1]
Consulting TDMX_ Template. m code

May I ask for 1 in the code
1.Subjects=importdata  ('') 
2 BOLD=importdata ('') 
3. good=importdata  ('') 
4. format=dlmread ('')? 

What is the format for the data at four positions, or rather, what type of data are they, 3D data or 2D data?

**Comment by ryraut** [comment]
1. various compatible file formats; read as string array
2. .mat file; Time x Space (vector of spatial units...so 2D matrix, where spatial units are vectorized)
3. .mat file; Vector with length = number of spatial units
4. various compatible file formats (e.g., text file); vector with length = number of time points

Adding to comments of main script, thank you!
